service: pdf-converter

plugins:
  - serverless-go-plugin

custom:
  go:
    supportedRuntimes: provided.al2
    buildProvidedRuntimeAsBootstrap: true
    cmd: GOARCH=arm64 GOOS=linux go build -ldflags="-s -w"
  config:
    bucketName: pdf-converter-storage

provider:
  name: aws
  versionFunctions: false
  region: "eu-central-1"
  profile: serverless-admin-profile
  endpointType: REGIONAL
  iam:
    role:
      name: pdf-converter-role
      tags:
        application: "pdf-converter"
        owner: "serverless"
      statements:
        - Effect: "Allow"
          Action:
            - "s3:*"
          Resource:
            - Fn::Join:
                - ""
                - - "arn:aws:s3:::"
                  - Ref: PdfConverterBucket
                  - "/*"
            - Fn::GetAtt:
                - PdfConverterBucket
                - Arn
  apiGateway:
    disableDefaultEndpoint: false
    minimumCompressionSize: 1024 # in bytes
  timeout: 30
  tags:
    application: "pdf-converter"
    owner: "serverless"
  stackTags:
    application: "pdf-converter"
    owner: "serverless"
  deploymentBucket:
    blockPublicAccess: true
    tags:
      application: "pdf-converter"
      owner: "serverless"
  environment:
    REGION: ${self:provider.region}

package:
  exclude:
    - .env
    - .vscode/**
    - .travis.yml
    - coverage/**
    - test/**

functions:
  converter:
    name: pdf-converter-converter
    handler: converter/src/handler.convert
    memorySize: 2048
    environment:
      BUCKET: ${self:custom.config.bucketName}
    events:
      - s3:
          bucket: ${self:custom.config.bucketName}
          event: s3:ObjectCreated:*
          existing: true
          forceDeploy: true
          rules:
            - prefix: staging/
  ping:
    name: pdf-converter-ping
    handler: converter/src/handler.ping
    memorySize: 512
    runtime: nodejs16.x
    events:
      - http:
          path: /api/v1/ping
          method: get
          cors: true
          #authorizer:
          #  arn: arn:aws:cognito-idp:eu-central-1:671123374425:userpool/eu-central-1_vcPfClzJm
  generate-upload-presigned-url:
    name: pdf-converter-generate-upload-presigned-url
    handler: generate-upload-presigned-url/main.go
    memorySize: 512
    architecture: arm64
    runtime: provided.al2
    environment:
      BUCKET: ${self:custom.config.bucketName}
    events:
      - http:
          path: /api/v1/presigned-urls
          method: post
          cors: true

resources:
  Resources:
    PdfConverterBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.config.bucketName}
        BucketEncryption:
          ServerSideEncryptionConfiguration:
            - ServerSideEncryptionByDefault:
                SSEAlgorithm: AES256
        AccessControl: Private
        PublicAccessBlockConfiguration:
          BlockPublicAcls: true
          BlockPublicPolicy: true
          IgnorePublicAcls: true
          RestrictPublicBuckets: true
